### ISSUE TITLE
apc.enable_cli has no effect

### ISSUE THREAD

**Issue by sebcmp** [edyan/docker-php#2]
https://github.com/edyan/docker-php/blob/master/files/common/php-fpm.ini#L14

apc.enable_cli has no effect, because it's placed in the php-fpm.ini not php-cli.ini

```sh
echo "apc.enable_cli=1" >> /etc/php/curren/cli/conf.d/30-custom-php.ini 
php -i| grep apc.enable_cl
apc.enable_cli => On => On
```

**Comment by edyan** [comment]
Hi, I am not sure to understand, if you need to override fpm settings, you can either mount the config (`php-fpm.ini`) or another custom into `/etc/php/current/fpm/user-conf.d/` such as `99-custom.conf`

**Comment by sebcmp** [comment]
Yes, the override is understood.

However, the custom php.ini settings (/etc/php/current/fpm/conf.d/30-custom-php.ini), that you distribute with the docker image, have above mentioned issues. 

The apc.enable_cli setting has no effect, because it's placed in the FPM php.ini not in the CLI php.ini

Also error_log = /var/log/php/php-fpm.log is not functioning as expected, since the path does not exists and PHP does not create the log by itself.

Yes, both issues don't cause any errors, but might be rather confusing to a user.

**Comment by edyan** [comment]
Hi @sebcmp  I have changed that. Thanks for your feedback. I have also updated all images. I had a few problems with memcached and went back to distros' version.  Can you have a look ?
