### ISSUE TITLE
php5.6 Jessie EOL

### ISSUE THREAD

**Issue by sebcmp** [edyan/docker-php#5]
Docker image fails building with GPG key errors

https://stackoverflow.com/questions/74531081/debian-8-jessie-archive-debian-org-gpg-error-keyexpired-since-2022-11-19-what-n

suggests using `debian/eol:jessie` as base image

https://hub.docker.com/r/debian/eol/#!

**Comment by edyan** [comment]
Hello and thanks. I took some time to do it but now everything is updated (all images, see the doc) with the best release for the php version and I use github actions to build / push it to registries, including ghcr.

Have a good day
